# Generated by Django 5.0.6 on 2025-01-13 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tsagaan_sar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner', models.CharField(max_length=100)),
                ('tailbar', models.CharField(max_length=100)),
                ('une', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nomiin_torol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TsagaanSariinNom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nom', to='nom.nom')),
                ('tsagaan_sar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tsagaan_sar', to='tsagaan_sar.tsagaansar')),
            ],
        ),
    ]
