# Generated by Django 5.0.6 on 2025-01-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nom',
            name='tailbar',
            field=models.CharField(max_length=400),
        ),
    ]
