# Generated by Django 5.0.6 on 2025-01-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nom', '0002_alter_nom_tailbar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TsagaanSariinNom',
        ),
    ]
