# Generated by Django 5.0.6 on 2025-02-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom', '0003_delete_tsagaansariinnom'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner', models.CharField(max_length=100)),
                ('tailbar', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='nom',
            name='online_zahialga_avah',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='NomBundleNom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nom.nom')),
                ('nom_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nom.nombundle')),
            ],
        ),
    ]
