# Generated by Django 5.0.6 on 2025-01-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TsagaanSar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner', models.CharField(max_length=100)),
                ('ognoo', models.DateField()),
            ],
        ),
    ]
