# Generated by Django 5.0.6 on 2025-01-21 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom', '0003_delete_tsagaansariinnom'),
        ('tsagaan_sar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TsagaanSarSuudal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suudal', models.CharField(choices=[('WATER', 'Ус'), ('WOOD', 'Мод'), ('WIND', 'Хий'), ('FIRE', 'Гал'), ('EARTH', 'Шороо'), ('METAL', 'Төмөр'), ('SPACE', 'Огторгуй'), ('MOUNTAIN', 'Уул')], max_length=100)),
                ('jil', models.CharField(choices=[('0', 'Хулгана'), ('1', 'Yхэр'), ('2', 'Бар'), ('3', 'Туулай'), ('4', 'Луу'), ('5', 'Могой'), ('6', 'Морь'), ('7', 'Хонь'), ('8', 'Бич'), ('9', 'Тахиа'), ('10', 'Нохой'), ('11', 'Гахай')], max_length=100)),
                ('huis', models.CharField(choices=[('MALE', 'Эрэгтэй'), ('FEMALE', 'Эмэгтэй')], max_length=100)),
                ('ognoo', models.DateField()),
                ('tsagaan_sar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsagaan_sar.tsagaansar')),
            ],
        ),
        migrations.CreateModel(
            name='TsagaaSarSuudalZasal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nom.nom')),
                ('tsagaan_sar_suudal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsagaan_sar.tsagaansarsuudal')),
            ],
        ),
    ]
