# Generated by Django 5.0.6 on 2025-01-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsagaan_sar', '0002_tsagaansarsuudal_tsagaasarsuudalzasal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsagaansarsuudal',
            name='jil',
            field=models.CharField(choices=[('MOUSE', 'Хулгана'), ('OX', 'Yхэр'), ('TIGER', 'Бар'), ('RABBIT', 'Туулай'), ('DRAGON', 'Луу'), ('SNAKE', 'Могой'), ('HORSE', 'Морь'), ('SHEEP', 'Хонь'), ('MONKEY', 'Бич'), ('ROOSTER', 'Тахиа'), ('DOG', 'Нохой'), ('PIG', 'Гахай')], max_length=100),
        ),
    ]
