# Generated by Django 5.0.6 on 2025-02-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsagaan_sar', '0003_alter_tsagaansarsuudal_jil'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigiinToolol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilgiin_toolol', models.CharField(max_length=100)),
                ('ognoo', models.DateField()),
            ],
        ),
    ]
