# Generated by Django 5.0.6 on 2025-01-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner', models.CharField(max_length=100)),
                ('utas', models.CharField(max_length=100)),
                ('huselt', models.CharField(max_length=500)),
            ],
        ),
    ]
