# Generated by Django 5.0.6 on 2025-01-27 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nom', '0003_delete_tsagaansariinnom'),
    ]

    operations = [
        migrations.CreateModel(
            name='QpayToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(max_length=20)),
                ('refresh_expires_in', models.IntegerField()),
                ('access_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('refresh_token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zahialga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid4', models.CharField(editable=False, max_length=255, unique=True)),
                ('utas', models.CharField(max_length=8)),
                ('ner', models.CharField(max_length=100)),
                ('hend', models.CharField(max_length=100)),
                ('jil', models.CharField(choices=[('MOUSE', 'Хулгана'), ('OX', 'Yхэр'), ('TIGER', 'Бар'), ('RABBIT', 'Туулай'), ('DRAGON', 'Луу'), ('SNAKE', 'Могой'), ('HORSE', 'Морь'), ('SHEEP', 'Хонь'), ('MONKEY', 'Бич'), ('ROOSTER', 'Тахиа'), ('DOG', 'Нохой'), ('PIG', 'Гахай')], max_length=100)),
                ('huis', models.CharField(choices=[('MALE', 'Эрэгтэй'), ('FEMALE', 'Эмэгтэй')], max_length=100)),
                ('tolov', models.CharField(choices=[('PENDING', 'Төлөгдөөгүй'), ('SUCCESS', 'Төлөгдсөн'), ('CANCELED', 'Цуцлагдсан')], default='PENDING', max_length=100)),
                ('torson_ognoo', models.DateField()),
                ('uniin_dun', models.IntegerField()),
                ('qpay_invoice_id', models.CharField(max_length=200, null=True)),
                ('qpay_qr_text', models.TextField(null=True)),
                ('qpay_qr_image', models.TextField(null=True)),
                ('qpay_shortUrl', models.TextField(null=True)),
                ('uussen_ognoo', models.DateField(auto_now_add=True)),
                ('shinechlegdsen_ognoo', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZahialgaDeepLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('logo', models.CharField(max_length=200, null=True)),
                ('link', models.TextField(null=True)),
                ('zahialga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahialga.zahialga')),
            ],
        ),
        migrations.CreateModel(
            name='ZahialgaNom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('une', models.IntegerField()),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nom.nom')),
                ('zahialga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahialga.zahialga')),
            ],
        ),
    ]
