# Generated by Django 5.0.6 on 2025-02-03 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahialga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZahialgaHural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mute_all', models.BooleanField(default=False)),
                ('zahialga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahialga.zahialga')),
            ],
        ),
    ]
