# Generated by Django 5.0.6 on 2025-02-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahialga', '0002_zahialgahural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zahialga',
            name='hend',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zahialga',
            name='ner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zahialga',
            name='torson_ognoo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zahialga',
            name='utas',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
