# Generated by Django 5.0.6 on 2025-04-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahialga', '0003_alter_zahialga_hend_alter_zahialga_ner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zahialga',
            name='shinechlegdsen_ognoo',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zahialga',
            name='uussen_ognoo',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
