# Generated by Django 5.0.6 on 2025-04-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahialga', '0004_alter_zahialga_shinechlegdsen_ognoo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zahialga',
            name='shinechlegdsen_ognoo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
